-- Budget Tool schema (Supabase / Postgres)
-- Generated from data-model.md, 2026-09-04
-- Run this in the Supabase SQL editor on a fresh project.

create type rollover_behavior as enum ('ROLLOVER', 'RESET');
create type disposition_target_type as enum ('CATEGORY', 'UNALLOCATED', 'EXITED');
create type allocation_source as enum ('RECURRING', 'MANUAL_OVERRIDE');
create type income_field as enum ('JASON_PAYCHECK_1', 'JASON_PAYCHECK_2', 'JAMIE_INCOME', 'OTHER');
create type account_type as enum ('CHECKING', 'CREDIT_CARD', 'SAVINGS', 'EXTERNAL');
create type transaction_type as enum ('PURCHASE', 'INCOME', 'TRANSFER', 'CREDIT_CARD_PAYMENT', 'EXTERNAL_FUNDING');
create type income_source as enum ('MY_INCOME', 'WIFE_INCOME', 'OTHER_INCOME');
create type categorization_status as enum ('UNCATEGORIZED', 'CATEGORIZED', 'EXCLUDED');
create type rule_created_from as enum ('MANUAL', 'LEARNED');
create type decision_type as enum ('NEGATIVE_COVERAGE', 'RESET_SURPLUS_DISPOSITION', 'INCOME_SURPLUS', 'INCOME_SHORTFALL', 'MANUAL_REALLOCATION');
create type disposition_source_type as enum ('CATEGORY', 'UNALLOCATED', 'EXTERNAL');

create table category_group (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int not null default 0
);

create table account (
  id bigint generated by default as identity primary key,
  name text not null,
  account_type account_type not null,
  plaid_account_id text,
  is_designated_savings_account boolean not null default false,
  is_tracked_credit_card boolean not null default false
);

-- "month" columns always store the first day of the month (e.g. 2026-09-01).
create table category (
  id bigint generated by default as identity primary key,
  group_id bigint not null references category_group(id),
  name text not null,
  rollover_behavior rollover_behavior not null,
  reset_default_disposition_type disposition_target_type,
  reset_default_disposition_category_id bigint references category(id),
  is_savings_transfer boolean not null default false,
  designated_savings_account_id bigint references account(id),
  active boolean not null default true
);

create table recurring_allocation_rule (
  id bigint generated by default as identity primary key,
  category_id bigint not null references category(id),
  amount numeric(12,2) not null,
  effective_start_month date not null,
  effective_end_month date,
  created_at timestamptz not null default now()
);

create table category_month (
  id bigint generated by default as identity primary key,
  category_id bigint not null references category(id),
  month date not null,
  allocation_amount numeric(12,2) not null,
  allocation_source allocation_source not null,
  rule_id bigint references recurring_allocation_rule(id),
  opening_balance numeric(12,2) not null default 0,
  note text,
  unique (category_id, month)
);

create table planned_income_rule (
  id bigint generated by default as identity primary key,
  income_field income_field not null,
  amount numeric(12,2) not null,
  effective_start_month date not null,
  effective_end_month date,
  created_at timestamptz not null default now()
);

create table planned_income_month (
  id bigint generated by default as identity primary key,
  income_field income_field not null,
  month date not null,
  amount numeric(12,2) not null,
  source allocation_source not null,
  rule_id bigint references planned_income_rule(id),
  unique (income_field, month)
);

create table "transaction" (
  id bigint generated by default as identity primary key,
  account_id bigint not null references account(id),
  plaid_pending_transaction_id text,
  plaid_posted_transaction_id text,
  budget_date date not null,        -- pending date; fixes the budget month, per design decision
  posted_date date,
  amount numeric(12,2) not null,    -- current/final known amount, updated in place on posting
  is_pending boolean not null default false,
  merchant_name text,
  description text,
  transaction_type transaction_type not null,
  income_source income_source,      -- set only when transaction_type = 'INCOME'
  categorization_status categorization_status not null default 'UNCATEGORIZED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table transaction_category_line (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references "transaction"(id) on delete cascade,
  category_id bigint not null references category(id),
  amount numeric(12,2) not null,
  note text
);

create table merchant_category_rule (
  id bigint generated by default as identity primary key,
  merchant_pattern text not null,
  category_id bigint not null references category(id),
  active boolean not null default true,
  created_from rule_created_from not null default 'MANUAL'
);

-- Budget-internal decision ledger. NOT bank transactions — see data-model.md.
create table disposition (
  id bigint generated by default as identity primary key,
  month date not null,
  decision_type decision_type not null,
  source_type disposition_source_type not null,
  source_category_id bigint references category(id),
  destination_type disposition_target_type not null,
  destination_category_id bigint references category(id),
  amount numeric(12,2) not null,
  applied_automatically boolean not null default false,
  note text,
  created_at timestamptz not null default now()
);

create table month_status (
  month date primary key,
  closed_at timestamptz
);

create table audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  field text not null,
  old_value text,
  new_value text,
  changed_at timestamptz not null default now(),
  note text
);

-- Row Level Security: this is a shared two-person household budget, not a
-- multi-tenant app. Both of you should see and edit the same data, so access
-- is gated only on "are you logged in," not per-row ownership (per spec §42,
-- which leaves permissions as a technical/product decision).
alter table category_group enable row level security;
alter table account enable row level security;
alter table category enable row level security;
alter table recurring_allocation_rule enable row level security;
alter table category_month enable row level security;
alter table planned_income_rule enable row level security;
alter table planned_income_month enable row level security;
alter table "transaction" enable row level security;
alter table transaction_category_line enable row level security;
alter table merchant_category_rule enable row level security;
alter table disposition enable row level security;
alter table month_status enable row level security;
alter table audit_log enable row level security;

create policy "household members full access" on category_group for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on account for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on category for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on recurring_allocation_rule for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on category_month for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on planned_income_rule for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on planned_income_month for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on "transaction" for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on transaction_category_line for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on merchant_category_rule for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on disposition for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on month_status for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "household members full access" on audit_log for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
